version: 0.1.0.{build}

os: Visual Studio 2019
image: Visual Studio 2019
skip_branch_with_pr: true

environment:
  AppVeyor: APPVEYOR

init:

- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq 'true')
    {
      $env:fileVersion = $env:APPVEYOR_REPO_TAG_NAME -replace '(\d+)\.(\d+)\.(\d+)(-.+)?', '$1.$2.$3'
      if ($env:fileVersion -eq $env:APPVEYOR_REPO_TAG_NAME) { $env:fileVersion = $($env:fileVersion + '.0') }
      else { $env:fileVersion = $($env:fileVersion + '.' + $env:APPVEYOR_BUILD_NUMBER) }
      $env:productVersion = $env:APPVEYOR_REPO_TAG_NAME
    }
    else
    {
      $env:fileVersion = $env:APPVEYOR_BUILD_VERSION -replace '(\d+)\.(\d+)\.([^.]+)\.(\d+)', '$1.$2.999.$4'
      $env:productVersion = $env:fileVersion
    }
    
    Update-AppveyorBuild -Version $env:fileVersion
    
    Write-Host $env:fileVersion $env:productVersion
    
    Write-Host $env:APPVEYOR_REPO_TAG $env:APPVEYOR_REPO_TAG_NAME


dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '$(productVersion)'
  package_version: '$(productVersion)'
  assembly_version: '$(fileVersion)'
  file_version: '$(fileVersion)'
  informational_version: '$(productVersion)'

# platform: Any CPU
configuration : 
- Release

before_build:
  - cmd: nuget update -self
  - nuget restore

build:
  parallel: true
  project: NoBox.sln
  verbosity: minimal

after_test:
  - choco install opencover.portable
  - choco install codecov
  - OpenCover.Console.exe -register:administrator -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test -c Debug --logger:trx;LogFileName=results.trx /p:DebugType=full src/NoBox.Tests/NoBox.Tests.csproj" -filter:"+[NoBox*]* -[*Tests*]*" -output:".\coverage.xml"
  - codecov -f .\coverage.xml -t $(codecov_token)

after_build:
  - cd src/NoBox/bin/%CONFIGURATION%/
  - 7z a NoBox_%productVersion%.zip */NoBox.dll
  - cd ../../../../

artifacts:
  - path: src/NoBox/bin/%CONFIGURATION%/*.zip
  - path: src/NoBox/bin/%CONFIGURATION%/*/NoBox.dll
  - path: src/NoBox/bin/%CONFIGURATION%/*.nupkg

nuget:
  project_feed: true
  disable_publish_on_pr: true

deploy:
- provider: GitHub
  artifact: /.*\.(zip|nupkg)/
  auth_token:
    secure: 5pdvVfRfTSSPchNZYeq2hjGiOOVmGiG//urbVC13tUO7rHYV6oP+1pXdU/tUn2/s
  draft: true
  on:
    APPVEYOR_REPO_TAG: true
- provider: NuGet
  artifact: /.*\.nupkg/
  api_key:
    secure: xvpb1BlgwEmZAlXCd2itV1ycCYyq4dvDtwGZ0HyzSPXgaTwvHUPu3yly9I/cgptt
  on:
    APPVEYOR_REPO_TAG: true
