//Generated with T4 templates
using System;

namespace Pankraty.NoBox.Tests.Common
{
    public static partial class CastSamples
    {
        #region Defaults for SimpleValue
        
        // Instances of SimpleValue build from CLR types (the correctness of such casts covered by separate tests)

        public static SimpleValue SimpleValue_bool => Default_bool;
        public static SimpleValue SimpleValue_sbyte => Default_sbyte;
        public static SimpleValue SimpleValue_byte => Default_byte;
        public static SimpleValue SimpleValue_short => Default_short;
        public static SimpleValue SimpleValue_ushort => Default_ushort;
        public static SimpleValue SimpleValue_int => Default_int;
        public static SimpleValue SimpleValue_uint => Default_uint;
        public static SimpleValue SimpleValue_long => Default_long;
        public static SimpleValue SimpleValue_ulong => Default_ulong;
        public static SimpleValue SimpleValue_float => Default_float;
        public static SimpleValue SimpleValue_double => Default_double;
        public static SimpleValue SimpleValue_char => Default_char;
        public static SimpleValue SimpleValue_DateTime => Default_DateTime;
        public static SimpleValue SimpleValue_DateTimeOffset => Default_DateTimeOffset;
        public static SimpleValue SimpleValue_TimeSpan => Default_TimeSpan;
        public static SimpleValue SimpleValue_Guid => Default_Guid;
        public static SimpleValue SimpleValue_decimal => Default_decimal;

        #endregion Defaults for SimpleValue

        #region Defaults for SimpleValueOr<String>
        
        // Instances of SimpleValueOr<String> build from CLR types (the correctness of such casts covered by separate tests)

        public static SimpleValueOr<String> SimpleValueOrString_bool => Default_bool;
        public static SimpleValueOr<String> SimpleValueOrString_sbyte => Default_sbyte;
        public static SimpleValueOr<String> SimpleValueOrString_byte => Default_byte;
        public static SimpleValueOr<String> SimpleValueOrString_short => Default_short;
        public static SimpleValueOr<String> SimpleValueOrString_ushort => Default_ushort;
        public static SimpleValueOr<String> SimpleValueOrString_int => Default_int;
        public static SimpleValueOr<String> SimpleValueOrString_uint => Default_uint;
        public static SimpleValueOr<String> SimpleValueOrString_long => Default_long;
        public static SimpleValueOr<String> SimpleValueOrString_ulong => Default_ulong;
        public static SimpleValueOr<String> SimpleValueOrString_float => Default_float;
        public static SimpleValueOr<String> SimpleValueOrString_double => Default_double;
        public static SimpleValueOr<String> SimpleValueOrString_char => Default_char;
        public static SimpleValueOr<String> SimpleValueOrString_DateTime => Default_DateTime;
        public static SimpleValueOr<String> SimpleValueOrString_DateTimeOffset => Default_DateTimeOffset;
        public static SimpleValueOr<String> SimpleValueOrString_TimeSpan => Default_TimeSpan;
        public static SimpleValueOr<String> SimpleValueOrString_Guid => Default_Guid;
        public static SimpleValueOr<String> SimpleValueOrString_decimal => Default_decimal;
        public static SimpleValueOr<String> SimpleValueOrString_string => Default_string;
        public static SimpleValueOr<String> SimpleValueOrString_SimpleValue => Default_SimpleValue;

        #endregion Defaults for SimpleValueOr<String>


        /// <summary>
        /// All casts that have to be covered with unit tests
        /// </summary>
        private static CastDefinition[] AllCasts =
        {
            #region From SimpleValue to every type
        
            new CastDefinition<SimpleValue, bool>(SimpleValue_bool, v => v, (bool)Default_bool),
            new CastDefinition<SimpleValue, sbyte>(SimpleValue_bool, v => v, invalidCastException),
            new CastDefinition<SimpleValue, byte>(SimpleValue_bool, v => v, invalidCastException),
            new CastDefinition<SimpleValue, short>(SimpleValue_bool, v => v, invalidCastException),
            new CastDefinition<SimpleValue, ushort>(SimpleValue_bool, v => v, invalidCastException),
            new CastDefinition<SimpleValue, int>(SimpleValue_bool, v => v, invalidCastException),
            new CastDefinition<SimpleValue, uint>(SimpleValue_bool, v => v, invalidCastException),
            new CastDefinition<SimpleValue, long>(SimpleValue_bool, v => v, invalidCastException),
            new CastDefinition<SimpleValue, ulong>(SimpleValue_bool, v => v, invalidCastException),
            new CastDefinition<SimpleValue, float>(SimpleValue_bool, v => v, invalidCastException),
            new CastDefinition<SimpleValue, double>(SimpleValue_bool, v => v, invalidCastException),
            new CastDefinition<SimpleValue, char>(SimpleValue_bool, v => v, invalidCastException),
            new CastDefinition<SimpleValue, DateTime>(SimpleValue_bool, v => v, invalidCastException),
            new CastDefinition<SimpleValue, DateTimeOffset>(SimpleValue_bool, v => v, invalidCastException),
            new CastDefinition<SimpleValue, TimeSpan>(SimpleValue_bool, v => v, invalidCastException),
            new CastDefinition<SimpleValue, Guid>(SimpleValue_bool, v => v, invalidCastException),
            new CastDefinition<SimpleValue, decimal>(SimpleValue_bool, v => v, invalidCastException),

            new CastDefinition<SimpleValue, bool>(SimpleValue_sbyte, v => v, invalidCastException),
            new CastDefinition<SimpleValue, sbyte>(SimpleValue_sbyte, v => v, (sbyte)Default_sbyte),
            new CastDefinition<SimpleValue, byte>(SimpleValue_sbyte, v => v, (byte)Default_sbyte),
            new CastDefinition<SimpleValue, short>(SimpleValue_sbyte, v => v, (short)Default_sbyte),
            new CastDefinition<SimpleValue, ushort>(SimpleValue_sbyte, v => v, (ushort)Default_sbyte),
            new CastDefinition<SimpleValue, int>(SimpleValue_sbyte, v => v, (int)Default_sbyte),
            new CastDefinition<SimpleValue, uint>(SimpleValue_sbyte, v => v, (uint)Default_sbyte),
            new CastDefinition<SimpleValue, long>(SimpleValue_sbyte, v => v, (long)Default_sbyte),
            new CastDefinition<SimpleValue, ulong>(SimpleValue_sbyte, v => v, (ulong)Default_sbyte),
            new CastDefinition<SimpleValue, float>(SimpleValue_sbyte, v => v, (float)Default_sbyte),
            new CastDefinition<SimpleValue, double>(SimpleValue_sbyte, v => v, (double)Default_sbyte),
            new CastDefinition<SimpleValue, char>(SimpleValue_sbyte, v => v, (char)Default_sbyte),
            new CastDefinition<SimpleValue, DateTime>(SimpleValue_sbyte, v => v, invalidCastException),
            new CastDefinition<SimpleValue, DateTimeOffset>(SimpleValue_sbyte, v => v, invalidCastException),
            new CastDefinition<SimpleValue, TimeSpan>(SimpleValue_sbyte, v => v, invalidCastException),
            new CastDefinition<SimpleValue, Guid>(SimpleValue_sbyte, v => v, invalidCastException),
            new CastDefinition<SimpleValue, decimal>(SimpleValue_sbyte, v => v, (decimal)Default_sbyte),

            new CastDefinition<SimpleValue, bool>(SimpleValue_byte, v => v, invalidCastException),
            new CastDefinition<SimpleValue, sbyte>(SimpleValue_byte, v => v, (sbyte)Default_byte),
            new CastDefinition<SimpleValue, byte>(SimpleValue_byte, v => v, (byte)Default_byte),
            new CastDefinition<SimpleValue, short>(SimpleValue_byte, v => v, (short)Default_byte),
            new CastDefinition<SimpleValue, ushort>(SimpleValue_byte, v => v, (ushort)Default_byte),
            new CastDefinition<SimpleValue, int>(SimpleValue_byte, v => v, (int)Default_byte),
            new CastDefinition<SimpleValue, uint>(SimpleValue_byte, v => v, (uint)Default_byte),
            new CastDefinition<SimpleValue, long>(SimpleValue_byte, v => v, (long)Default_byte),
            new CastDefinition<SimpleValue, ulong>(SimpleValue_byte, v => v, (ulong)Default_byte),
            new CastDefinition<SimpleValue, float>(SimpleValue_byte, v => v, (float)Default_byte),
            new CastDefinition<SimpleValue, double>(SimpleValue_byte, v => v, (double)Default_byte),
            new CastDefinition<SimpleValue, char>(SimpleValue_byte, v => v, (char)Default_byte),
            new CastDefinition<SimpleValue, DateTime>(SimpleValue_byte, v => v, invalidCastException),
            new CastDefinition<SimpleValue, DateTimeOffset>(SimpleValue_byte, v => v, invalidCastException),
            new CastDefinition<SimpleValue, TimeSpan>(SimpleValue_byte, v => v, invalidCastException),
            new CastDefinition<SimpleValue, Guid>(SimpleValue_byte, v => v, invalidCastException),
            new CastDefinition<SimpleValue, decimal>(SimpleValue_byte, v => v, (decimal)Default_byte),

            new CastDefinition<SimpleValue, bool>(SimpleValue_short, v => v, invalidCastException),
            new CastDefinition<SimpleValue, sbyte>(SimpleValue_short, v => v, (sbyte)Default_short),
            new CastDefinition<SimpleValue, byte>(SimpleValue_short, v => v, (byte)Default_short),
            new CastDefinition<SimpleValue, short>(SimpleValue_short, v => v, (short)Default_short),
            new CastDefinition<SimpleValue, ushort>(SimpleValue_short, v => v, (ushort)Default_short),
            new CastDefinition<SimpleValue, int>(SimpleValue_short, v => v, (int)Default_short),
            new CastDefinition<SimpleValue, uint>(SimpleValue_short, v => v, (uint)Default_short),
            new CastDefinition<SimpleValue, long>(SimpleValue_short, v => v, (long)Default_short),
            new CastDefinition<SimpleValue, ulong>(SimpleValue_short, v => v, (ulong)Default_short),
            new CastDefinition<SimpleValue, float>(SimpleValue_short, v => v, (float)Default_short),
            new CastDefinition<SimpleValue, double>(SimpleValue_short, v => v, (double)Default_short),
            new CastDefinition<SimpleValue, char>(SimpleValue_short, v => v, (char)Default_short),
            new CastDefinition<SimpleValue, DateTime>(SimpleValue_short, v => v, invalidCastException),
            new CastDefinition<SimpleValue, DateTimeOffset>(SimpleValue_short, v => v, invalidCastException),
            new CastDefinition<SimpleValue, TimeSpan>(SimpleValue_short, v => v, invalidCastException),
            new CastDefinition<SimpleValue, Guid>(SimpleValue_short, v => v, invalidCastException),
            new CastDefinition<SimpleValue, decimal>(SimpleValue_short, v => v, (decimal)Default_short),

            new CastDefinition<SimpleValue, bool>(SimpleValue_ushort, v => v, invalidCastException),
            new CastDefinition<SimpleValue, sbyte>(SimpleValue_ushort, v => v, (sbyte)Default_ushort),
            new CastDefinition<SimpleValue, byte>(SimpleValue_ushort, v => v, (byte)Default_ushort),
            new CastDefinition<SimpleValue, short>(SimpleValue_ushort, v => v, (short)Default_ushort),
            new CastDefinition<SimpleValue, ushort>(SimpleValue_ushort, v => v, (ushort)Default_ushort),
            new CastDefinition<SimpleValue, int>(SimpleValue_ushort, v => v, (int)Default_ushort),
            new CastDefinition<SimpleValue, uint>(SimpleValue_ushort, v => v, (uint)Default_ushort),
            new CastDefinition<SimpleValue, long>(SimpleValue_ushort, v => v, (long)Default_ushort),
            new CastDefinition<SimpleValue, ulong>(SimpleValue_ushort, v => v, (ulong)Default_ushort),
            new CastDefinition<SimpleValue, float>(SimpleValue_ushort, v => v, (float)Default_ushort),
            new CastDefinition<SimpleValue, double>(SimpleValue_ushort, v => v, (double)Default_ushort),
            new CastDefinition<SimpleValue, char>(SimpleValue_ushort, v => v, (char)Default_ushort),
            new CastDefinition<SimpleValue, DateTime>(SimpleValue_ushort, v => v, invalidCastException),
            new CastDefinition<SimpleValue, DateTimeOffset>(SimpleValue_ushort, v => v, invalidCastException),
            new CastDefinition<SimpleValue, TimeSpan>(SimpleValue_ushort, v => v, invalidCastException),
            new CastDefinition<SimpleValue, Guid>(SimpleValue_ushort, v => v, invalidCastException),
            new CastDefinition<SimpleValue, decimal>(SimpleValue_ushort, v => v, (decimal)Default_ushort),

            new CastDefinition<SimpleValue, bool>(SimpleValue_int, v => v, invalidCastException),
            new CastDefinition<SimpleValue, sbyte>(SimpleValue_int, v => v, (sbyte)Default_int),
            new CastDefinition<SimpleValue, byte>(SimpleValue_int, v => v, (byte)Default_int),
            new CastDefinition<SimpleValue, short>(SimpleValue_int, v => v, (short)Default_int),
            new CastDefinition<SimpleValue, ushort>(SimpleValue_int, v => v, (ushort)Default_int),
            new CastDefinition<SimpleValue, int>(SimpleValue_int, v => v, (int)Default_int),
            new CastDefinition<SimpleValue, uint>(SimpleValue_int, v => v, (uint)Default_int),
            new CastDefinition<SimpleValue, long>(SimpleValue_int, v => v, (long)Default_int),
            new CastDefinition<SimpleValue, ulong>(SimpleValue_int, v => v, (ulong)Default_int),
            new CastDefinition<SimpleValue, float>(SimpleValue_int, v => v, (float)Default_int),
            new CastDefinition<SimpleValue, double>(SimpleValue_int, v => v, (double)Default_int),
            new CastDefinition<SimpleValue, char>(SimpleValue_int, v => v, (char)Default_int),
            new CastDefinition<SimpleValue, DateTime>(SimpleValue_int, v => v, invalidCastException),
            new CastDefinition<SimpleValue, DateTimeOffset>(SimpleValue_int, v => v, invalidCastException),
            new CastDefinition<SimpleValue, TimeSpan>(SimpleValue_int, v => v, invalidCastException),
            new CastDefinition<SimpleValue, Guid>(SimpleValue_int, v => v, invalidCastException),
            new CastDefinition<SimpleValue, decimal>(SimpleValue_int, v => v, (decimal)Default_int),

            new CastDefinition<SimpleValue, bool>(SimpleValue_uint, v => v, invalidCastException),
            new CastDefinition<SimpleValue, sbyte>(SimpleValue_uint, v => v, (sbyte)Default_uint),
            new CastDefinition<SimpleValue, byte>(SimpleValue_uint, v => v, (byte)Default_uint),
            new CastDefinition<SimpleValue, short>(SimpleValue_uint, v => v, (short)Default_uint),
            new CastDefinition<SimpleValue, ushort>(SimpleValue_uint, v => v, (ushort)Default_uint),
            new CastDefinition<SimpleValue, int>(SimpleValue_uint, v => v, (int)Default_uint),
            new CastDefinition<SimpleValue, uint>(SimpleValue_uint, v => v, (uint)Default_uint),
            new CastDefinition<SimpleValue, long>(SimpleValue_uint, v => v, (long)Default_uint),
            new CastDefinition<SimpleValue, ulong>(SimpleValue_uint, v => v, (ulong)Default_uint),
            new CastDefinition<SimpleValue, float>(SimpleValue_uint, v => v, (float)Default_uint),
            new CastDefinition<SimpleValue, double>(SimpleValue_uint, v => v, (double)Default_uint),
            new CastDefinition<SimpleValue, char>(SimpleValue_uint, v => v, (char)Default_uint),
            new CastDefinition<SimpleValue, DateTime>(SimpleValue_uint, v => v, invalidCastException),
            new CastDefinition<SimpleValue, DateTimeOffset>(SimpleValue_uint, v => v, invalidCastException),
            new CastDefinition<SimpleValue, TimeSpan>(SimpleValue_uint, v => v, invalidCastException),
            new CastDefinition<SimpleValue, Guid>(SimpleValue_uint, v => v, invalidCastException),
            new CastDefinition<SimpleValue, decimal>(SimpleValue_uint, v => v, (decimal)Default_uint),

            new CastDefinition<SimpleValue, bool>(SimpleValue_long, v => v, invalidCastException),
            new CastDefinition<SimpleValue, sbyte>(SimpleValue_long, v => v, (sbyte)Default_long),
            new CastDefinition<SimpleValue, byte>(SimpleValue_long, v => v, (byte)Default_long),
            new CastDefinition<SimpleValue, short>(SimpleValue_long, v => v, (short)Default_long),
            new CastDefinition<SimpleValue, ushort>(SimpleValue_long, v => v, (ushort)Default_long),
            new CastDefinition<SimpleValue, int>(SimpleValue_long, v => v, (int)Default_long),
            new CastDefinition<SimpleValue, uint>(SimpleValue_long, v => v, (uint)Default_long),
            new CastDefinition<SimpleValue, long>(SimpleValue_long, v => v, (long)Default_long),
            new CastDefinition<SimpleValue, ulong>(SimpleValue_long, v => v, (ulong)Default_long),
            new CastDefinition<SimpleValue, float>(SimpleValue_long, v => v, (float)Default_long),
            new CastDefinition<SimpleValue, double>(SimpleValue_long, v => v, (double)Default_long),
            new CastDefinition<SimpleValue, char>(SimpleValue_long, v => v, (char)Default_long),
            new CastDefinition<SimpleValue, DateTime>(SimpleValue_long, v => v, invalidCastException),
            new CastDefinition<SimpleValue, DateTimeOffset>(SimpleValue_long, v => v, invalidCastException),
            new CastDefinition<SimpleValue, TimeSpan>(SimpleValue_long, v => v, invalidCastException),
            new CastDefinition<SimpleValue, Guid>(SimpleValue_long, v => v, invalidCastException),
            new CastDefinition<SimpleValue, decimal>(SimpleValue_long, v => v, (decimal)Default_long),

            new CastDefinition<SimpleValue, bool>(SimpleValue_ulong, v => v, invalidCastException),
            new CastDefinition<SimpleValue, sbyte>(SimpleValue_ulong, v => v, (sbyte)Default_ulong),
            new CastDefinition<SimpleValue, byte>(SimpleValue_ulong, v => v, (byte)Default_ulong),
            new CastDefinition<SimpleValue, short>(SimpleValue_ulong, v => v, (short)Default_ulong),
            new CastDefinition<SimpleValue, ushort>(SimpleValue_ulong, v => v, (ushort)Default_ulong),
            new CastDefinition<SimpleValue, int>(SimpleValue_ulong, v => v, (int)Default_ulong),
            new CastDefinition<SimpleValue, uint>(SimpleValue_ulong, v => v, (uint)Default_ulong),
            new CastDefinition<SimpleValue, long>(SimpleValue_ulong, v => v, (long)Default_ulong),
            new CastDefinition<SimpleValue, ulong>(SimpleValue_ulong, v => v, (ulong)Default_ulong),
            new CastDefinition<SimpleValue, float>(SimpleValue_ulong, v => v, (float)Default_ulong),
            new CastDefinition<SimpleValue, double>(SimpleValue_ulong, v => v, (double)Default_ulong),
            new CastDefinition<SimpleValue, char>(SimpleValue_ulong, v => v, (char)Default_ulong),
            new CastDefinition<SimpleValue, DateTime>(SimpleValue_ulong, v => v, invalidCastException),
            new CastDefinition<SimpleValue, DateTimeOffset>(SimpleValue_ulong, v => v, invalidCastException),
            new CastDefinition<SimpleValue, TimeSpan>(SimpleValue_ulong, v => v, invalidCastException),
            new CastDefinition<SimpleValue, Guid>(SimpleValue_ulong, v => v, invalidCastException),
            new CastDefinition<SimpleValue, decimal>(SimpleValue_ulong, v => v, (decimal)Default_ulong),

            new CastDefinition<SimpleValue, bool>(SimpleValue_float, v => v, invalidCastException),
            new CastDefinition<SimpleValue, sbyte>(SimpleValue_float, v => v, (sbyte)Default_float),
            new CastDefinition<SimpleValue, byte>(SimpleValue_float, v => v, (byte)Default_float),
            new CastDefinition<SimpleValue, short>(SimpleValue_float, v => v, (short)Default_float),
            new CastDefinition<SimpleValue, ushort>(SimpleValue_float, v => v, (ushort)Default_float),
            new CastDefinition<SimpleValue, int>(SimpleValue_float, v => v, (int)Default_float),
            new CastDefinition<SimpleValue, uint>(SimpleValue_float, v => v, (uint)Default_float),
            new CastDefinition<SimpleValue, long>(SimpleValue_float, v => v, (long)Default_float),
            new CastDefinition<SimpleValue, ulong>(SimpleValue_float, v => v, (ulong)Default_float),
            new CastDefinition<SimpleValue, float>(SimpleValue_float, v => v, (float)Default_float),
            new CastDefinition<SimpleValue, double>(SimpleValue_float, v => v, (double)Default_float),
            new CastDefinition<SimpleValue, char>(SimpleValue_float, v => v, (char)Default_float),
            new CastDefinition<SimpleValue, DateTime>(SimpleValue_float, v => v, invalidCastException),
            new CastDefinition<SimpleValue, DateTimeOffset>(SimpleValue_float, v => v, invalidCastException),
            new CastDefinition<SimpleValue, TimeSpan>(SimpleValue_float, v => v, invalidCastException),
            new CastDefinition<SimpleValue, Guid>(SimpleValue_float, v => v, invalidCastException),
            new CastDefinition<SimpleValue, decimal>(SimpleValue_float, v => v, (decimal)Default_float),

            new CastDefinition<SimpleValue, bool>(SimpleValue_double, v => v, invalidCastException),
            new CastDefinition<SimpleValue, sbyte>(SimpleValue_double, v => v, (sbyte)Default_double),
            new CastDefinition<SimpleValue, byte>(SimpleValue_double, v => v, (byte)Default_double),
            new CastDefinition<SimpleValue, short>(SimpleValue_double, v => v, (short)Default_double),
            new CastDefinition<SimpleValue, ushort>(SimpleValue_double, v => v, (ushort)Default_double),
            new CastDefinition<SimpleValue, int>(SimpleValue_double, v => v, (int)Default_double),
            new CastDefinition<SimpleValue, uint>(SimpleValue_double, v => v, (uint)Default_double),
            new CastDefinition<SimpleValue, long>(SimpleValue_double, v => v, (long)Default_double),
            new CastDefinition<SimpleValue, ulong>(SimpleValue_double, v => v, (ulong)Default_double),
            new CastDefinition<SimpleValue, float>(SimpleValue_double, v => v, (float)Default_double),
            new CastDefinition<SimpleValue, double>(SimpleValue_double, v => v, (double)Default_double),
            new CastDefinition<SimpleValue, char>(SimpleValue_double, v => v, (char)Default_double),
            new CastDefinition<SimpleValue, DateTime>(SimpleValue_double, v => v, invalidCastException),
            new CastDefinition<SimpleValue, DateTimeOffset>(SimpleValue_double, v => v, invalidCastException),
            new CastDefinition<SimpleValue, TimeSpan>(SimpleValue_double, v => v, invalidCastException),
            new CastDefinition<SimpleValue, Guid>(SimpleValue_double, v => v, invalidCastException),
            new CastDefinition<SimpleValue, decimal>(SimpleValue_double, v => v, (decimal)Default_double),

            new CastDefinition<SimpleValue, bool>(SimpleValue_char, v => v, invalidCastException),
            new CastDefinition<SimpleValue, sbyte>(SimpleValue_char, v => v, (sbyte)Default_char),
            new CastDefinition<SimpleValue, byte>(SimpleValue_char, v => v, (byte)Default_char),
            new CastDefinition<SimpleValue, short>(SimpleValue_char, v => v, (short)Default_char),
            new CastDefinition<SimpleValue, ushort>(SimpleValue_char, v => v, (ushort)Default_char),
            new CastDefinition<SimpleValue, int>(SimpleValue_char, v => v, (int)Default_char),
            new CastDefinition<SimpleValue, uint>(SimpleValue_char, v => v, (uint)Default_char),
            new CastDefinition<SimpleValue, long>(SimpleValue_char, v => v, (long)Default_char),
            new CastDefinition<SimpleValue, ulong>(SimpleValue_char, v => v, (ulong)Default_char),
            new CastDefinition<SimpleValue, float>(SimpleValue_char, v => v, (float)Default_char),
            new CastDefinition<SimpleValue, double>(SimpleValue_char, v => v, (double)Default_char),
            new CastDefinition<SimpleValue, char>(SimpleValue_char, v => v, (char)Default_char),
            new CastDefinition<SimpleValue, DateTime>(SimpleValue_char, v => v, invalidCastException),
            new CastDefinition<SimpleValue, DateTimeOffset>(SimpleValue_char, v => v, invalidCastException),
            new CastDefinition<SimpleValue, TimeSpan>(SimpleValue_char, v => v, invalidCastException),
            new CastDefinition<SimpleValue, Guid>(SimpleValue_char, v => v, invalidCastException),
            new CastDefinition<SimpleValue, decimal>(SimpleValue_char, v => v, (decimal)Default_char),

            new CastDefinition<SimpleValue, bool>(SimpleValue_DateTime, v => v, invalidCastException),
            new CastDefinition<SimpleValue, sbyte>(SimpleValue_DateTime, v => v, invalidCastException),
            new CastDefinition<SimpleValue, byte>(SimpleValue_DateTime, v => v, invalidCastException),
            new CastDefinition<SimpleValue, short>(SimpleValue_DateTime, v => v, invalidCastException),
            new CastDefinition<SimpleValue, ushort>(SimpleValue_DateTime, v => v, invalidCastException),
            new CastDefinition<SimpleValue, int>(SimpleValue_DateTime, v => v, invalidCastException),
            new CastDefinition<SimpleValue, uint>(SimpleValue_DateTime, v => v, invalidCastException),
            new CastDefinition<SimpleValue, long>(SimpleValue_DateTime, v => v, invalidCastException),
            new CastDefinition<SimpleValue, ulong>(SimpleValue_DateTime, v => v, invalidCastException),
            new CastDefinition<SimpleValue, float>(SimpleValue_DateTime, v => v, invalidCastException),
            new CastDefinition<SimpleValue, double>(SimpleValue_DateTime, v => v, invalidCastException),
            new CastDefinition<SimpleValue, char>(SimpleValue_DateTime, v => v, invalidCastException),
            new CastDefinition<SimpleValue, DateTime>(SimpleValue_DateTime, v => v, (DateTime)Default_DateTime),
            new CastDefinition<SimpleValue, DateTimeOffset>(SimpleValue_DateTime, v => v, (DateTimeOffset)Default_DateTime),
            new CastDefinition<SimpleValue, TimeSpan>(SimpleValue_DateTime, v => v, invalidCastException),
            new CastDefinition<SimpleValue, Guid>(SimpleValue_DateTime, v => v, invalidCastException),
            new CastDefinition<SimpleValue, decimal>(SimpleValue_DateTime, v => v, invalidCastException),

            new CastDefinition<SimpleValue, bool>(SimpleValue_DateTimeOffset, v => v, invalidCastException),
            new CastDefinition<SimpleValue, sbyte>(SimpleValue_DateTimeOffset, v => v, invalidCastException),
            new CastDefinition<SimpleValue, byte>(SimpleValue_DateTimeOffset, v => v, invalidCastException),
            new CastDefinition<SimpleValue, short>(SimpleValue_DateTimeOffset, v => v, invalidCastException),
            new CastDefinition<SimpleValue, ushort>(SimpleValue_DateTimeOffset, v => v, invalidCastException),
            new CastDefinition<SimpleValue, int>(SimpleValue_DateTimeOffset, v => v, invalidCastException),
            new CastDefinition<SimpleValue, uint>(SimpleValue_DateTimeOffset, v => v, invalidCastException),
            new CastDefinition<SimpleValue, long>(SimpleValue_DateTimeOffset, v => v, invalidCastException),
            new CastDefinition<SimpleValue, ulong>(SimpleValue_DateTimeOffset, v => v, invalidCastException),
            new CastDefinition<SimpleValue, float>(SimpleValue_DateTimeOffset, v => v, invalidCastException),
            new CastDefinition<SimpleValue, double>(SimpleValue_DateTimeOffset, v => v, invalidCastException),
            new CastDefinition<SimpleValue, char>(SimpleValue_DateTimeOffset, v => v, invalidCastException),
            new CastDefinition<SimpleValue, DateTime>(SimpleValue_DateTimeOffset, v => v, invalidCastException),
            new CastDefinition<SimpleValue, DateTimeOffset>(SimpleValue_DateTimeOffset, v => v, (DateTimeOffset)Default_DateTimeOffset),
            new CastDefinition<SimpleValue, TimeSpan>(SimpleValue_DateTimeOffset, v => v, invalidCastException),
            new CastDefinition<SimpleValue, Guid>(SimpleValue_DateTimeOffset, v => v, invalidCastException),
            new CastDefinition<SimpleValue, decimal>(SimpleValue_DateTimeOffset, v => v, invalidCastException),

            new CastDefinition<SimpleValue, bool>(SimpleValue_TimeSpan, v => v, invalidCastException),
            new CastDefinition<SimpleValue, sbyte>(SimpleValue_TimeSpan, v => v, invalidCastException),
            new CastDefinition<SimpleValue, byte>(SimpleValue_TimeSpan, v => v, invalidCastException),
            new CastDefinition<SimpleValue, short>(SimpleValue_TimeSpan, v => v, invalidCastException),
            new CastDefinition<SimpleValue, ushort>(SimpleValue_TimeSpan, v => v, invalidCastException),
            new CastDefinition<SimpleValue, int>(SimpleValue_TimeSpan, v => v, invalidCastException),
            new CastDefinition<SimpleValue, uint>(SimpleValue_TimeSpan, v => v, invalidCastException),
            new CastDefinition<SimpleValue, long>(SimpleValue_TimeSpan, v => v, invalidCastException),
            new CastDefinition<SimpleValue, ulong>(SimpleValue_TimeSpan, v => v, invalidCastException),
            new CastDefinition<SimpleValue, float>(SimpleValue_TimeSpan, v => v, invalidCastException),
            new CastDefinition<SimpleValue, double>(SimpleValue_TimeSpan, v => v, invalidCastException),
            new CastDefinition<SimpleValue, char>(SimpleValue_TimeSpan, v => v, invalidCastException),
            new CastDefinition<SimpleValue, DateTime>(SimpleValue_TimeSpan, v => v, invalidCastException),
            new CastDefinition<SimpleValue, DateTimeOffset>(SimpleValue_TimeSpan, v => v, invalidCastException),
            new CastDefinition<SimpleValue, TimeSpan>(SimpleValue_TimeSpan, v => v, (TimeSpan)Default_TimeSpan),
            new CastDefinition<SimpleValue, Guid>(SimpleValue_TimeSpan, v => v, invalidCastException),
            new CastDefinition<SimpleValue, decimal>(SimpleValue_TimeSpan, v => v, invalidCastException),

            new CastDefinition<SimpleValue, bool>(SimpleValue_Guid, v => v, invalidCastException),
            new CastDefinition<SimpleValue, sbyte>(SimpleValue_Guid, v => v, invalidCastException),
            new CastDefinition<SimpleValue, byte>(SimpleValue_Guid, v => v, invalidCastException),
            new CastDefinition<SimpleValue, short>(SimpleValue_Guid, v => v, invalidCastException),
            new CastDefinition<SimpleValue, ushort>(SimpleValue_Guid, v => v, invalidCastException),
            new CastDefinition<SimpleValue, int>(SimpleValue_Guid, v => v, invalidCastException),
            new CastDefinition<SimpleValue, uint>(SimpleValue_Guid, v => v, invalidCastException),
            new CastDefinition<SimpleValue, long>(SimpleValue_Guid, v => v, invalidCastException),
            new CastDefinition<SimpleValue, ulong>(SimpleValue_Guid, v => v, invalidCastException),
            new CastDefinition<SimpleValue, float>(SimpleValue_Guid, v => v, invalidCastException),
            new CastDefinition<SimpleValue, double>(SimpleValue_Guid, v => v, invalidCastException),
            new CastDefinition<SimpleValue, char>(SimpleValue_Guid, v => v, invalidCastException),
            new CastDefinition<SimpleValue, DateTime>(SimpleValue_Guid, v => v, invalidCastException),
            new CastDefinition<SimpleValue, DateTimeOffset>(SimpleValue_Guid, v => v, invalidCastException),
            new CastDefinition<SimpleValue, TimeSpan>(SimpleValue_Guid, v => v, invalidCastException),
            new CastDefinition<SimpleValue, Guid>(SimpleValue_Guid, v => v, (Guid)Default_Guid),
            new CastDefinition<SimpleValue, decimal>(SimpleValue_Guid, v => v, invalidCastException),

            new CastDefinition<SimpleValue, bool>(SimpleValue_decimal, v => v, invalidCastException),
            new CastDefinition<SimpleValue, sbyte>(SimpleValue_decimal, v => v, (sbyte)Default_decimal),
            new CastDefinition<SimpleValue, byte>(SimpleValue_decimal, v => v, (byte)Default_decimal),
            new CastDefinition<SimpleValue, short>(SimpleValue_decimal, v => v, (short)Default_decimal),
            new CastDefinition<SimpleValue, ushort>(SimpleValue_decimal, v => v, (ushort)Default_decimal),
            new CastDefinition<SimpleValue, int>(SimpleValue_decimal, v => v, (int)Default_decimal),
            new CastDefinition<SimpleValue, uint>(SimpleValue_decimal, v => v, (uint)Default_decimal),
            new CastDefinition<SimpleValue, long>(SimpleValue_decimal, v => v, (long)Default_decimal),
            new CastDefinition<SimpleValue, ulong>(SimpleValue_decimal, v => v, (ulong)Default_decimal),
            new CastDefinition<SimpleValue, float>(SimpleValue_decimal, v => v, (float)Default_decimal),
            new CastDefinition<SimpleValue, double>(SimpleValue_decimal, v => v, (double)Default_decimal),
            new CastDefinition<SimpleValue, char>(SimpleValue_decimal, v => v, (char)Default_decimal),
            new CastDefinition<SimpleValue, DateTime>(SimpleValue_decimal, v => v, invalidCastException),
            new CastDefinition<SimpleValue, DateTimeOffset>(SimpleValue_decimal, v => v, invalidCastException),
            new CastDefinition<SimpleValue, TimeSpan>(SimpleValue_decimal, v => v, invalidCastException),
            new CastDefinition<SimpleValue, Guid>(SimpleValue_decimal, v => v, invalidCastException),
            new CastDefinition<SimpleValue, decimal>(SimpleValue_decimal, v => v, (decimal)Default_decimal),

            #endregion From SimpleValue to every type

            #region From SimpleValueOr<String> to every type
        
            new CastDefinition<SimpleValueOr<String>, bool>(SimpleValueOrString_bool, v => v, (bool)Default_bool),
            new CastDefinition<SimpleValueOr<String>, sbyte>(SimpleValueOrString_bool, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, byte>(SimpleValueOrString_bool, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, short>(SimpleValueOrString_bool, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, ushort>(SimpleValueOrString_bool, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, int>(SimpleValueOrString_bool, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, uint>(SimpleValueOrString_bool, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, long>(SimpleValueOrString_bool, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, ulong>(SimpleValueOrString_bool, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, float>(SimpleValueOrString_bool, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, double>(SimpleValueOrString_bool, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, char>(SimpleValueOrString_bool, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, DateTime>(SimpleValueOrString_bool, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, DateTimeOffset>(SimpleValueOrString_bool, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, TimeSpan>(SimpleValueOrString_bool, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, Guid>(SimpleValueOrString_bool, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, decimal>(SimpleValueOrString_bool, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, string>(SimpleValueOrString_bool, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, SimpleValue>(SimpleValueOrString_bool, v => v, (SimpleValue)Default_bool),

            new CastDefinition<SimpleValueOr<String>, bool>(SimpleValueOrString_sbyte, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, sbyte>(SimpleValueOrString_sbyte, v => v, (sbyte)Default_sbyte),
            new CastDefinition<SimpleValueOr<String>, byte>(SimpleValueOrString_sbyte, v => v, (byte)Default_sbyte),
            new CastDefinition<SimpleValueOr<String>, short>(SimpleValueOrString_sbyte, v => v, (short)Default_sbyte),
            new CastDefinition<SimpleValueOr<String>, ushort>(SimpleValueOrString_sbyte, v => v, (ushort)Default_sbyte),
            new CastDefinition<SimpleValueOr<String>, int>(SimpleValueOrString_sbyte, v => v, (int)Default_sbyte),
            new CastDefinition<SimpleValueOr<String>, uint>(SimpleValueOrString_sbyte, v => v, (uint)Default_sbyte),
            new CastDefinition<SimpleValueOr<String>, long>(SimpleValueOrString_sbyte, v => v, (long)Default_sbyte),
            new CastDefinition<SimpleValueOr<String>, ulong>(SimpleValueOrString_sbyte, v => v, (ulong)Default_sbyte),
            new CastDefinition<SimpleValueOr<String>, float>(SimpleValueOrString_sbyte, v => v, (float)Default_sbyte),
            new CastDefinition<SimpleValueOr<String>, double>(SimpleValueOrString_sbyte, v => v, (double)Default_sbyte),
            new CastDefinition<SimpleValueOr<String>, char>(SimpleValueOrString_sbyte, v => v, (char)Default_sbyte),
            new CastDefinition<SimpleValueOr<String>, DateTime>(SimpleValueOrString_sbyte, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, DateTimeOffset>(SimpleValueOrString_sbyte, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, TimeSpan>(SimpleValueOrString_sbyte, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, Guid>(SimpleValueOrString_sbyte, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, decimal>(SimpleValueOrString_sbyte, v => v, (decimal)Default_sbyte),
            new CastDefinition<SimpleValueOr<String>, string>(SimpleValueOrString_sbyte, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, SimpleValue>(SimpleValueOrString_sbyte, v => v, (SimpleValue)Default_sbyte),

            new CastDefinition<SimpleValueOr<String>, bool>(SimpleValueOrString_byte, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, sbyte>(SimpleValueOrString_byte, v => v, (sbyte)Default_byte),
            new CastDefinition<SimpleValueOr<String>, byte>(SimpleValueOrString_byte, v => v, (byte)Default_byte),
            new CastDefinition<SimpleValueOr<String>, short>(SimpleValueOrString_byte, v => v, (short)Default_byte),
            new CastDefinition<SimpleValueOr<String>, ushort>(SimpleValueOrString_byte, v => v, (ushort)Default_byte),
            new CastDefinition<SimpleValueOr<String>, int>(SimpleValueOrString_byte, v => v, (int)Default_byte),
            new CastDefinition<SimpleValueOr<String>, uint>(SimpleValueOrString_byte, v => v, (uint)Default_byte),
            new CastDefinition<SimpleValueOr<String>, long>(SimpleValueOrString_byte, v => v, (long)Default_byte),
            new CastDefinition<SimpleValueOr<String>, ulong>(SimpleValueOrString_byte, v => v, (ulong)Default_byte),
            new CastDefinition<SimpleValueOr<String>, float>(SimpleValueOrString_byte, v => v, (float)Default_byte),
            new CastDefinition<SimpleValueOr<String>, double>(SimpleValueOrString_byte, v => v, (double)Default_byte),
            new CastDefinition<SimpleValueOr<String>, char>(SimpleValueOrString_byte, v => v, (char)Default_byte),
            new CastDefinition<SimpleValueOr<String>, DateTime>(SimpleValueOrString_byte, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, DateTimeOffset>(SimpleValueOrString_byte, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, TimeSpan>(SimpleValueOrString_byte, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, Guid>(SimpleValueOrString_byte, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, decimal>(SimpleValueOrString_byte, v => v, (decimal)Default_byte),
            new CastDefinition<SimpleValueOr<String>, string>(SimpleValueOrString_byte, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, SimpleValue>(SimpleValueOrString_byte, v => v, (SimpleValue)Default_byte),

            new CastDefinition<SimpleValueOr<String>, bool>(SimpleValueOrString_short, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, sbyte>(SimpleValueOrString_short, v => v, (sbyte)Default_short),
            new CastDefinition<SimpleValueOr<String>, byte>(SimpleValueOrString_short, v => v, (byte)Default_short),
            new CastDefinition<SimpleValueOr<String>, short>(SimpleValueOrString_short, v => v, (short)Default_short),
            new CastDefinition<SimpleValueOr<String>, ushort>(SimpleValueOrString_short, v => v, (ushort)Default_short),
            new CastDefinition<SimpleValueOr<String>, int>(SimpleValueOrString_short, v => v, (int)Default_short),
            new CastDefinition<SimpleValueOr<String>, uint>(SimpleValueOrString_short, v => v, (uint)Default_short),
            new CastDefinition<SimpleValueOr<String>, long>(SimpleValueOrString_short, v => v, (long)Default_short),
            new CastDefinition<SimpleValueOr<String>, ulong>(SimpleValueOrString_short, v => v, (ulong)Default_short),
            new CastDefinition<SimpleValueOr<String>, float>(SimpleValueOrString_short, v => v, (float)Default_short),
            new CastDefinition<SimpleValueOr<String>, double>(SimpleValueOrString_short, v => v, (double)Default_short),
            new CastDefinition<SimpleValueOr<String>, char>(SimpleValueOrString_short, v => v, (char)Default_short),
            new CastDefinition<SimpleValueOr<String>, DateTime>(SimpleValueOrString_short, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, DateTimeOffset>(SimpleValueOrString_short, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, TimeSpan>(SimpleValueOrString_short, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, Guid>(SimpleValueOrString_short, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, decimal>(SimpleValueOrString_short, v => v, (decimal)Default_short),
            new CastDefinition<SimpleValueOr<String>, string>(SimpleValueOrString_short, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, SimpleValue>(SimpleValueOrString_short, v => v, (SimpleValue)Default_short),

            new CastDefinition<SimpleValueOr<String>, bool>(SimpleValueOrString_ushort, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, sbyte>(SimpleValueOrString_ushort, v => v, (sbyte)Default_ushort),
            new CastDefinition<SimpleValueOr<String>, byte>(SimpleValueOrString_ushort, v => v, (byte)Default_ushort),
            new CastDefinition<SimpleValueOr<String>, short>(SimpleValueOrString_ushort, v => v, (short)Default_ushort),
            new CastDefinition<SimpleValueOr<String>, ushort>(SimpleValueOrString_ushort, v => v, (ushort)Default_ushort),
            new CastDefinition<SimpleValueOr<String>, int>(SimpleValueOrString_ushort, v => v, (int)Default_ushort),
            new CastDefinition<SimpleValueOr<String>, uint>(SimpleValueOrString_ushort, v => v, (uint)Default_ushort),
            new CastDefinition<SimpleValueOr<String>, long>(SimpleValueOrString_ushort, v => v, (long)Default_ushort),
            new CastDefinition<SimpleValueOr<String>, ulong>(SimpleValueOrString_ushort, v => v, (ulong)Default_ushort),
            new CastDefinition<SimpleValueOr<String>, float>(SimpleValueOrString_ushort, v => v, (float)Default_ushort),
            new CastDefinition<SimpleValueOr<String>, double>(SimpleValueOrString_ushort, v => v, (double)Default_ushort),
            new CastDefinition<SimpleValueOr<String>, char>(SimpleValueOrString_ushort, v => v, (char)Default_ushort),
            new CastDefinition<SimpleValueOr<String>, DateTime>(SimpleValueOrString_ushort, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, DateTimeOffset>(SimpleValueOrString_ushort, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, TimeSpan>(SimpleValueOrString_ushort, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, Guid>(SimpleValueOrString_ushort, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, decimal>(SimpleValueOrString_ushort, v => v, (decimal)Default_ushort),
            new CastDefinition<SimpleValueOr<String>, string>(SimpleValueOrString_ushort, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, SimpleValue>(SimpleValueOrString_ushort, v => v, (SimpleValue)Default_ushort),

            new CastDefinition<SimpleValueOr<String>, bool>(SimpleValueOrString_int, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, sbyte>(SimpleValueOrString_int, v => v, (sbyte)Default_int),
            new CastDefinition<SimpleValueOr<String>, byte>(SimpleValueOrString_int, v => v, (byte)Default_int),
            new CastDefinition<SimpleValueOr<String>, short>(SimpleValueOrString_int, v => v, (short)Default_int),
            new CastDefinition<SimpleValueOr<String>, ushort>(SimpleValueOrString_int, v => v, (ushort)Default_int),
            new CastDefinition<SimpleValueOr<String>, int>(SimpleValueOrString_int, v => v, (int)Default_int),
            new CastDefinition<SimpleValueOr<String>, uint>(SimpleValueOrString_int, v => v, (uint)Default_int),
            new CastDefinition<SimpleValueOr<String>, long>(SimpleValueOrString_int, v => v, (long)Default_int),
            new CastDefinition<SimpleValueOr<String>, ulong>(SimpleValueOrString_int, v => v, (ulong)Default_int),
            new CastDefinition<SimpleValueOr<String>, float>(SimpleValueOrString_int, v => v, (float)Default_int),
            new CastDefinition<SimpleValueOr<String>, double>(SimpleValueOrString_int, v => v, (double)Default_int),
            new CastDefinition<SimpleValueOr<String>, char>(SimpleValueOrString_int, v => v, (char)Default_int),
            new CastDefinition<SimpleValueOr<String>, DateTime>(SimpleValueOrString_int, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, DateTimeOffset>(SimpleValueOrString_int, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, TimeSpan>(SimpleValueOrString_int, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, Guid>(SimpleValueOrString_int, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, decimal>(SimpleValueOrString_int, v => v, (decimal)Default_int),
            new CastDefinition<SimpleValueOr<String>, string>(SimpleValueOrString_int, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, SimpleValue>(SimpleValueOrString_int, v => v, (SimpleValue)Default_int),

            new CastDefinition<SimpleValueOr<String>, bool>(SimpleValueOrString_uint, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, sbyte>(SimpleValueOrString_uint, v => v, (sbyte)Default_uint),
            new CastDefinition<SimpleValueOr<String>, byte>(SimpleValueOrString_uint, v => v, (byte)Default_uint),
            new CastDefinition<SimpleValueOr<String>, short>(SimpleValueOrString_uint, v => v, (short)Default_uint),
            new CastDefinition<SimpleValueOr<String>, ushort>(SimpleValueOrString_uint, v => v, (ushort)Default_uint),
            new CastDefinition<SimpleValueOr<String>, int>(SimpleValueOrString_uint, v => v, (int)Default_uint),
            new CastDefinition<SimpleValueOr<String>, uint>(SimpleValueOrString_uint, v => v, (uint)Default_uint),
            new CastDefinition<SimpleValueOr<String>, long>(SimpleValueOrString_uint, v => v, (long)Default_uint),
            new CastDefinition<SimpleValueOr<String>, ulong>(SimpleValueOrString_uint, v => v, (ulong)Default_uint),
            new CastDefinition<SimpleValueOr<String>, float>(SimpleValueOrString_uint, v => v, (float)Default_uint),
            new CastDefinition<SimpleValueOr<String>, double>(SimpleValueOrString_uint, v => v, (double)Default_uint),
            new CastDefinition<SimpleValueOr<String>, char>(SimpleValueOrString_uint, v => v, (char)Default_uint),
            new CastDefinition<SimpleValueOr<String>, DateTime>(SimpleValueOrString_uint, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, DateTimeOffset>(SimpleValueOrString_uint, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, TimeSpan>(SimpleValueOrString_uint, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, Guid>(SimpleValueOrString_uint, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, decimal>(SimpleValueOrString_uint, v => v, (decimal)Default_uint),
            new CastDefinition<SimpleValueOr<String>, string>(SimpleValueOrString_uint, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, SimpleValue>(SimpleValueOrString_uint, v => v, (SimpleValue)Default_uint),

            new CastDefinition<SimpleValueOr<String>, bool>(SimpleValueOrString_long, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, sbyte>(SimpleValueOrString_long, v => v, (sbyte)Default_long),
            new CastDefinition<SimpleValueOr<String>, byte>(SimpleValueOrString_long, v => v, (byte)Default_long),
            new CastDefinition<SimpleValueOr<String>, short>(SimpleValueOrString_long, v => v, (short)Default_long),
            new CastDefinition<SimpleValueOr<String>, ushort>(SimpleValueOrString_long, v => v, (ushort)Default_long),
            new CastDefinition<SimpleValueOr<String>, int>(SimpleValueOrString_long, v => v, (int)Default_long),
            new CastDefinition<SimpleValueOr<String>, uint>(SimpleValueOrString_long, v => v, (uint)Default_long),
            new CastDefinition<SimpleValueOr<String>, long>(SimpleValueOrString_long, v => v, (long)Default_long),
            new CastDefinition<SimpleValueOr<String>, ulong>(SimpleValueOrString_long, v => v, (ulong)Default_long),
            new CastDefinition<SimpleValueOr<String>, float>(SimpleValueOrString_long, v => v, (float)Default_long),
            new CastDefinition<SimpleValueOr<String>, double>(SimpleValueOrString_long, v => v, (double)Default_long),
            new CastDefinition<SimpleValueOr<String>, char>(SimpleValueOrString_long, v => v, (char)Default_long),
            new CastDefinition<SimpleValueOr<String>, DateTime>(SimpleValueOrString_long, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, DateTimeOffset>(SimpleValueOrString_long, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, TimeSpan>(SimpleValueOrString_long, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, Guid>(SimpleValueOrString_long, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, decimal>(SimpleValueOrString_long, v => v, (decimal)Default_long),
            new CastDefinition<SimpleValueOr<String>, string>(SimpleValueOrString_long, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, SimpleValue>(SimpleValueOrString_long, v => v, (SimpleValue)Default_long),

            new CastDefinition<SimpleValueOr<String>, bool>(SimpleValueOrString_ulong, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, sbyte>(SimpleValueOrString_ulong, v => v, (sbyte)Default_ulong),
            new CastDefinition<SimpleValueOr<String>, byte>(SimpleValueOrString_ulong, v => v, (byte)Default_ulong),
            new CastDefinition<SimpleValueOr<String>, short>(SimpleValueOrString_ulong, v => v, (short)Default_ulong),
            new CastDefinition<SimpleValueOr<String>, ushort>(SimpleValueOrString_ulong, v => v, (ushort)Default_ulong),
            new CastDefinition<SimpleValueOr<String>, int>(SimpleValueOrString_ulong, v => v, (int)Default_ulong),
            new CastDefinition<SimpleValueOr<String>, uint>(SimpleValueOrString_ulong, v => v, (uint)Default_ulong),
            new CastDefinition<SimpleValueOr<String>, long>(SimpleValueOrString_ulong, v => v, (long)Default_ulong),
            new CastDefinition<SimpleValueOr<String>, ulong>(SimpleValueOrString_ulong, v => v, (ulong)Default_ulong),
            new CastDefinition<SimpleValueOr<String>, float>(SimpleValueOrString_ulong, v => v, (float)Default_ulong),
            new CastDefinition<SimpleValueOr<String>, double>(SimpleValueOrString_ulong, v => v, (double)Default_ulong),
            new CastDefinition<SimpleValueOr<String>, char>(SimpleValueOrString_ulong, v => v, (char)Default_ulong),
            new CastDefinition<SimpleValueOr<String>, DateTime>(SimpleValueOrString_ulong, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, DateTimeOffset>(SimpleValueOrString_ulong, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, TimeSpan>(SimpleValueOrString_ulong, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, Guid>(SimpleValueOrString_ulong, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, decimal>(SimpleValueOrString_ulong, v => v, (decimal)Default_ulong),
            new CastDefinition<SimpleValueOr<String>, string>(SimpleValueOrString_ulong, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, SimpleValue>(SimpleValueOrString_ulong, v => v, (SimpleValue)Default_ulong),

            new CastDefinition<SimpleValueOr<String>, bool>(SimpleValueOrString_float, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, sbyte>(SimpleValueOrString_float, v => v, (sbyte)Default_float),
            new CastDefinition<SimpleValueOr<String>, byte>(SimpleValueOrString_float, v => v, (byte)Default_float),
            new CastDefinition<SimpleValueOr<String>, short>(SimpleValueOrString_float, v => v, (short)Default_float),
            new CastDefinition<SimpleValueOr<String>, ushort>(SimpleValueOrString_float, v => v, (ushort)Default_float),
            new CastDefinition<SimpleValueOr<String>, int>(SimpleValueOrString_float, v => v, (int)Default_float),
            new CastDefinition<SimpleValueOr<String>, uint>(SimpleValueOrString_float, v => v, (uint)Default_float),
            new CastDefinition<SimpleValueOr<String>, long>(SimpleValueOrString_float, v => v, (long)Default_float),
            new CastDefinition<SimpleValueOr<String>, ulong>(SimpleValueOrString_float, v => v, (ulong)Default_float),
            new CastDefinition<SimpleValueOr<String>, float>(SimpleValueOrString_float, v => v, (float)Default_float),
            new CastDefinition<SimpleValueOr<String>, double>(SimpleValueOrString_float, v => v, (double)Default_float),
            new CastDefinition<SimpleValueOr<String>, char>(SimpleValueOrString_float, v => v, (char)Default_float),
            new CastDefinition<SimpleValueOr<String>, DateTime>(SimpleValueOrString_float, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, DateTimeOffset>(SimpleValueOrString_float, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, TimeSpan>(SimpleValueOrString_float, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, Guid>(SimpleValueOrString_float, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, decimal>(SimpleValueOrString_float, v => v, (decimal)Default_float),
            new CastDefinition<SimpleValueOr<String>, string>(SimpleValueOrString_float, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, SimpleValue>(SimpleValueOrString_float, v => v, (SimpleValue)Default_float),

            new CastDefinition<SimpleValueOr<String>, bool>(SimpleValueOrString_double, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, sbyte>(SimpleValueOrString_double, v => v, (sbyte)Default_double),
            new CastDefinition<SimpleValueOr<String>, byte>(SimpleValueOrString_double, v => v, (byte)Default_double),
            new CastDefinition<SimpleValueOr<String>, short>(SimpleValueOrString_double, v => v, (short)Default_double),
            new CastDefinition<SimpleValueOr<String>, ushort>(SimpleValueOrString_double, v => v, (ushort)Default_double),
            new CastDefinition<SimpleValueOr<String>, int>(SimpleValueOrString_double, v => v, (int)Default_double),
            new CastDefinition<SimpleValueOr<String>, uint>(SimpleValueOrString_double, v => v, (uint)Default_double),
            new CastDefinition<SimpleValueOr<String>, long>(SimpleValueOrString_double, v => v, (long)Default_double),
            new CastDefinition<SimpleValueOr<String>, ulong>(SimpleValueOrString_double, v => v, (ulong)Default_double),
            new CastDefinition<SimpleValueOr<String>, float>(SimpleValueOrString_double, v => v, (float)Default_double),
            new CastDefinition<SimpleValueOr<String>, double>(SimpleValueOrString_double, v => v, (double)Default_double),
            new CastDefinition<SimpleValueOr<String>, char>(SimpleValueOrString_double, v => v, (char)Default_double),
            new CastDefinition<SimpleValueOr<String>, DateTime>(SimpleValueOrString_double, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, DateTimeOffset>(SimpleValueOrString_double, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, TimeSpan>(SimpleValueOrString_double, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, Guid>(SimpleValueOrString_double, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, decimal>(SimpleValueOrString_double, v => v, (decimal)Default_double),
            new CastDefinition<SimpleValueOr<String>, string>(SimpleValueOrString_double, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, SimpleValue>(SimpleValueOrString_double, v => v, (SimpleValue)Default_double),

            new CastDefinition<SimpleValueOr<String>, bool>(SimpleValueOrString_char, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, sbyte>(SimpleValueOrString_char, v => v, (sbyte)Default_char),
            new CastDefinition<SimpleValueOr<String>, byte>(SimpleValueOrString_char, v => v, (byte)Default_char),
            new CastDefinition<SimpleValueOr<String>, short>(SimpleValueOrString_char, v => v, (short)Default_char),
            new CastDefinition<SimpleValueOr<String>, ushort>(SimpleValueOrString_char, v => v, (ushort)Default_char),
            new CastDefinition<SimpleValueOr<String>, int>(SimpleValueOrString_char, v => v, (int)Default_char),
            new CastDefinition<SimpleValueOr<String>, uint>(SimpleValueOrString_char, v => v, (uint)Default_char),
            new CastDefinition<SimpleValueOr<String>, long>(SimpleValueOrString_char, v => v, (long)Default_char),
            new CastDefinition<SimpleValueOr<String>, ulong>(SimpleValueOrString_char, v => v, (ulong)Default_char),
            new CastDefinition<SimpleValueOr<String>, float>(SimpleValueOrString_char, v => v, (float)Default_char),
            new CastDefinition<SimpleValueOr<String>, double>(SimpleValueOrString_char, v => v, (double)Default_char),
            new CastDefinition<SimpleValueOr<String>, char>(SimpleValueOrString_char, v => v, (char)Default_char),
            new CastDefinition<SimpleValueOr<String>, DateTime>(SimpleValueOrString_char, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, DateTimeOffset>(SimpleValueOrString_char, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, TimeSpan>(SimpleValueOrString_char, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, Guid>(SimpleValueOrString_char, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, decimal>(SimpleValueOrString_char, v => v, (decimal)Default_char),
            new CastDefinition<SimpleValueOr<String>, string>(SimpleValueOrString_char, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, SimpleValue>(SimpleValueOrString_char, v => v, (SimpleValue)Default_char),

            new CastDefinition<SimpleValueOr<String>, bool>(SimpleValueOrString_DateTime, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, sbyte>(SimpleValueOrString_DateTime, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, byte>(SimpleValueOrString_DateTime, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, short>(SimpleValueOrString_DateTime, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, ushort>(SimpleValueOrString_DateTime, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, int>(SimpleValueOrString_DateTime, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, uint>(SimpleValueOrString_DateTime, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, long>(SimpleValueOrString_DateTime, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, ulong>(SimpleValueOrString_DateTime, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, float>(SimpleValueOrString_DateTime, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, double>(SimpleValueOrString_DateTime, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, char>(SimpleValueOrString_DateTime, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, DateTime>(SimpleValueOrString_DateTime, v => v, (DateTime)Default_DateTime),
            new CastDefinition<SimpleValueOr<String>, DateTimeOffset>(SimpleValueOrString_DateTime, v => v, (DateTimeOffset)Default_DateTime),
            new CastDefinition<SimpleValueOr<String>, TimeSpan>(SimpleValueOrString_DateTime, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, Guid>(SimpleValueOrString_DateTime, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, decimal>(SimpleValueOrString_DateTime, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, string>(SimpleValueOrString_DateTime, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, SimpleValue>(SimpleValueOrString_DateTime, v => v, (SimpleValue)Default_DateTime),

            new CastDefinition<SimpleValueOr<String>, bool>(SimpleValueOrString_DateTimeOffset, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, sbyte>(SimpleValueOrString_DateTimeOffset, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, byte>(SimpleValueOrString_DateTimeOffset, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, short>(SimpleValueOrString_DateTimeOffset, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, ushort>(SimpleValueOrString_DateTimeOffset, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, int>(SimpleValueOrString_DateTimeOffset, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, uint>(SimpleValueOrString_DateTimeOffset, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, long>(SimpleValueOrString_DateTimeOffset, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, ulong>(SimpleValueOrString_DateTimeOffset, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, float>(SimpleValueOrString_DateTimeOffset, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, double>(SimpleValueOrString_DateTimeOffset, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, char>(SimpleValueOrString_DateTimeOffset, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, DateTime>(SimpleValueOrString_DateTimeOffset, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, DateTimeOffset>(SimpleValueOrString_DateTimeOffset, v => v, (DateTimeOffset)Default_DateTimeOffset),
            new CastDefinition<SimpleValueOr<String>, TimeSpan>(SimpleValueOrString_DateTimeOffset, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, Guid>(SimpleValueOrString_DateTimeOffset, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, decimal>(SimpleValueOrString_DateTimeOffset, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, string>(SimpleValueOrString_DateTimeOffset, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, SimpleValue>(SimpleValueOrString_DateTimeOffset, v => v, (SimpleValue)Default_DateTimeOffset),

            new CastDefinition<SimpleValueOr<String>, bool>(SimpleValueOrString_TimeSpan, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, sbyte>(SimpleValueOrString_TimeSpan, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, byte>(SimpleValueOrString_TimeSpan, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, short>(SimpleValueOrString_TimeSpan, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, ushort>(SimpleValueOrString_TimeSpan, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, int>(SimpleValueOrString_TimeSpan, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, uint>(SimpleValueOrString_TimeSpan, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, long>(SimpleValueOrString_TimeSpan, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, ulong>(SimpleValueOrString_TimeSpan, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, float>(SimpleValueOrString_TimeSpan, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, double>(SimpleValueOrString_TimeSpan, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, char>(SimpleValueOrString_TimeSpan, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, DateTime>(SimpleValueOrString_TimeSpan, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, DateTimeOffset>(SimpleValueOrString_TimeSpan, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, TimeSpan>(SimpleValueOrString_TimeSpan, v => v, (TimeSpan)Default_TimeSpan),
            new CastDefinition<SimpleValueOr<String>, Guid>(SimpleValueOrString_TimeSpan, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, decimal>(SimpleValueOrString_TimeSpan, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, string>(SimpleValueOrString_TimeSpan, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, SimpleValue>(SimpleValueOrString_TimeSpan, v => v, (SimpleValue)Default_TimeSpan),

            new CastDefinition<SimpleValueOr<String>, bool>(SimpleValueOrString_Guid, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, sbyte>(SimpleValueOrString_Guid, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, byte>(SimpleValueOrString_Guid, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, short>(SimpleValueOrString_Guid, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, ushort>(SimpleValueOrString_Guid, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, int>(SimpleValueOrString_Guid, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, uint>(SimpleValueOrString_Guid, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, long>(SimpleValueOrString_Guid, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, ulong>(SimpleValueOrString_Guid, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, float>(SimpleValueOrString_Guid, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, double>(SimpleValueOrString_Guid, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, char>(SimpleValueOrString_Guid, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, DateTime>(SimpleValueOrString_Guid, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, DateTimeOffset>(SimpleValueOrString_Guid, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, TimeSpan>(SimpleValueOrString_Guid, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, Guid>(SimpleValueOrString_Guid, v => v, (Guid)Default_Guid),
            new CastDefinition<SimpleValueOr<String>, decimal>(SimpleValueOrString_Guid, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, string>(SimpleValueOrString_Guid, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, SimpleValue>(SimpleValueOrString_Guid, v => v, (SimpleValue)Default_Guid),

            new CastDefinition<SimpleValueOr<String>, bool>(SimpleValueOrString_decimal, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, sbyte>(SimpleValueOrString_decimal, v => v, (sbyte)Default_decimal),
            new CastDefinition<SimpleValueOr<String>, byte>(SimpleValueOrString_decimal, v => v, (byte)Default_decimal),
            new CastDefinition<SimpleValueOr<String>, short>(SimpleValueOrString_decimal, v => v, (short)Default_decimal),
            new CastDefinition<SimpleValueOr<String>, ushort>(SimpleValueOrString_decimal, v => v, (ushort)Default_decimal),
            new CastDefinition<SimpleValueOr<String>, int>(SimpleValueOrString_decimal, v => v, (int)Default_decimal),
            new CastDefinition<SimpleValueOr<String>, uint>(SimpleValueOrString_decimal, v => v, (uint)Default_decimal),
            new CastDefinition<SimpleValueOr<String>, long>(SimpleValueOrString_decimal, v => v, (long)Default_decimal),
            new CastDefinition<SimpleValueOr<String>, ulong>(SimpleValueOrString_decimal, v => v, (ulong)Default_decimal),
            new CastDefinition<SimpleValueOr<String>, float>(SimpleValueOrString_decimal, v => v, (float)Default_decimal),
            new CastDefinition<SimpleValueOr<String>, double>(SimpleValueOrString_decimal, v => v, (double)Default_decimal),
            new CastDefinition<SimpleValueOr<String>, char>(SimpleValueOrString_decimal, v => v, (char)Default_decimal),
            new CastDefinition<SimpleValueOr<String>, DateTime>(SimpleValueOrString_decimal, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, DateTimeOffset>(SimpleValueOrString_decimal, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, TimeSpan>(SimpleValueOrString_decimal, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, Guid>(SimpleValueOrString_decimal, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, decimal>(SimpleValueOrString_decimal, v => v, (decimal)Default_decimal),
            new CastDefinition<SimpleValueOr<String>, string>(SimpleValueOrString_decimal, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, SimpleValue>(SimpleValueOrString_decimal, v => v, (SimpleValue)Default_decimal),

            new CastDefinition<SimpleValueOr<String>, bool>(SimpleValueOrString_string, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, sbyte>(SimpleValueOrString_string, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, byte>(SimpleValueOrString_string, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, short>(SimpleValueOrString_string, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, ushort>(SimpleValueOrString_string, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, int>(SimpleValueOrString_string, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, uint>(SimpleValueOrString_string, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, long>(SimpleValueOrString_string, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, ulong>(SimpleValueOrString_string, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, float>(SimpleValueOrString_string, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, double>(SimpleValueOrString_string, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, char>(SimpleValueOrString_string, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, DateTime>(SimpleValueOrString_string, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, DateTimeOffset>(SimpleValueOrString_string, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, TimeSpan>(SimpleValueOrString_string, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, Guid>(SimpleValueOrString_string, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, decimal>(SimpleValueOrString_string, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, string>(SimpleValueOrString_string, v => v, (string)Default_string),
            new CastDefinition<SimpleValueOr<String>, SimpleValue>(SimpleValueOrString_string, v => v, invalidCastException),

            new CastDefinition<SimpleValueOr<String>, string>(SimpleValueOrString_SimpleValue, v => v, invalidCastException),
            new CastDefinition<SimpleValueOr<String>, SimpleValue>(SimpleValueOrString_SimpleValue, v => v, (SimpleValue)Default_SimpleValue),

            #endregion From SimpleValueOr<String> to every type

        };
    }
}

